name: Packaging

on:
  push:
    tags:
      - 'v*'
  release:
    types:
      - created

jobs:
  package:
    strategy:
      matrix:
        # linux-arm, macos, win-msvc, win-gnu, win32-msvc]
        build: [linux,]
        include:
          - build: linux
            os: ubuntu-18.04
            target: x86_64-unknown-linux-gnu
        # - build: linux-arm
        #   os: ubuntu-18.04
        #   rust: nightly
        #   target: arm-unknown-linux-gnueabihf
        # - build: macos
        #   os: macos-latest
        #   rust: nightly
        #   target: x86_64-apple-darwin
        # - build: win-msvc
        #   os: windows-2019
        #   rust: nightly
        #   target: x86_64-pc-windows-msvc
        # - build: win-gnu
        #   os: windows-2019
        #   rust: nightly-x86_64-gnu
        #   target: x86_64-pc-windows-gnu
        # - build: win32-msvc
        #   os: windows-2019
        #   rust: nightly
        #   target: i686-pc-windows-msvc

  
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Check
        run: cargo check
      - name: Configure Git
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "action@github.com"
          curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
      - name: Build
        run: |
          cargo install cross
          cross build --release --target=${{ matrix.target }}
      - name: Attach Binary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          find . -name "semantic-release && cd ./target/ && ls && tar -czvf ${{ matrix.target }}
          ./bin/hub release -m "" --attach ./target/${{ matrix.target }} ${{ github.ref }}
